NUTCH-3078 Unlock database when Injector finishes - regardless of result
apache/nutch pull request #829
Opened 2024-10-15 06:06 UTC by HiranChaudhuri

2024-10-15 10:12 UTC, sebastian-nagel requested changes

2024-10-15 10:12 UTC, sebastian-nagel commented on src/java/org/apache/nutch/crawl/Injector.java
>      Path lock = CrawlDb.lock(conf, crawlDb, false);
See the discussion in NUTH-3078: moving the creating of the lockfile down just before the job is run would avoid that a failure during job configuration leads to a lost lockfile.

2024-10-15 17:19 UTC, sebastian-nagel approved these changes
Thanks,  @HiranChaudhuri!

I've also verified that this solution fixes the issue with the lockfile if the seed URL directory does not exists.

2024-10-15 17:19 UTC, sebastian-nagel commented on src/java/org/apache/nutch/crawl/Injector.java
>      Path lock = CrawlDb.lock(conf, crawlDb, false);
Great!

2024-10-20 22:26 UTC, lewismc approved these changes
+1 nice PR @HiranChaudhuri

2024-10-23 17:42 UTC, merged